name: bandit
dependencies:
  - abseil-cpp=20230802.0
  - absl-py=1.4.0
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=2.120
  - blas-devel=3.9.0
  - blinker=1.6.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - clarabel=0.6.0
  - click=8.1.7
  - cryptography=41.0.3
  - cvxpy=1.4.1
  - cvxpy-base=1.4.1
  - ecos=2.0.12
  - filelock=3.13.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.22.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - idna=3.4
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libffi=3.4.4


  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.25
  - libosqp=0.6.3
  - libprotobuf=3.20.3
  - libqdldl=0.1.7
  - libsqlite=3.44.2
  - libuv=1.44.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - ncurses=6.4
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.2
  - numpy-base=1.26.2
  - oauthlib=3.2.2
  - openblas=0.3.25
  - openssl=3.2.0
  - osqp=0.6.3
  - packaging=23.1
  - pip=23.3.1
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - pytorch=2.1.0
  - pyyaml=6.0.1
  - qdldl-python=0.1.7
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.11.4
  - scs=3.2.3
  - setuptools=68.0.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.41.2
  - sympy=1.12
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.13
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.2.13
  - pip:
    - asttokens==2.4.1
    - black==23.11.0
    - decorator==5.1.1
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - ipdb==0.13.13
    - ipython==8.18.1
    - jedi==0.19.1
    - matplotlib-inline==0.1.6
    - mypy-extensions==1.0.0
    - parso==0.8.3
    - pathspec==0.11.2
    - pexpect==4.9.0
    - platformdirs==4.1.0
    - prompt-toolkit==3.0.41
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.17.2
    - stack-data==0.6.3
    - tomli==2.0.1
    - traitlets==5.14.0
    - wcwidth==0.2.12
