state_dim: 2
action_num: 8
group_num: 3
pref_data_num: 300
batch_size: 300
dpo_num_iters: 20000
step_size: 0.1
reg_coef: 1.0
exp_step_size: 0.01
eval_metric: 'argmax'
param_limit: 5
chi: 1
C: 0

reward_param: "[[2.3,1.7,2.3,1.7],[2.0,2.0,2.0,2.0],[1.7,2.3,1.7,2.3]]"
test_weights: "[1,1,1]"

weighted_batches: "False"
exp_adaptive: 0
rdpo_adj: '0'
use_closed_form: "False"
val_deterministic: "False"
lamba: 0
l2_reg_rdpo: 0
use_uneven_grp: "False"
use_uneven_grp_val: "False"
use_theory: "False"
importance_sampling_weights: 'None'
flipped_noise: "True"

wandb:
  project: "noisy_exp_paper_2"
  group: 'group_exp'

feature_types:
  - "same" # swapped, flipped

noise_levels:
  - 0.0
  - 0.1
  - 0.2
  - 0.3
  - 0.4

data_sizes: 
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1.0

noise_ratio_template: "[noise_level,0,0]"
val_noise_ratio_list: "[0,0,0]"

data_ratio_template: "[1,1,data_size]"
val_weights: "[1,1,1]"

seeds:
  - 2021
  - 2022
  - 2023
  - 2024
  - 2025
  - 2026
  - 2027
  - 2028
  - 2029
  - 2030
